### ISSUE TITLE
Programming Patient Management System - First steps

### ISSUE THREAD

**Issue by inamtyulhaq** [inamtyulhaq/Object-Oriented-Programming-ITF22#2]
@mirzara04 I request you to kindly read all the assignment details and start working on developing the program. We will have a meeting regarding code efficiency later on.

**Comment by inamtyulhaq** [comment]
Mistakes do happen. I am reassigning the issue to Mir Zara.

**Comment by mirzara04** [comment]
I've started working on the assignment as we discussed earlier. I'll keep you updated on the progress.
